In [3]:
import numpy as np

In [4]:
def low(M,i): # Returns the "lowest" (in position) non-zero value 
              #in the column i
    
    # Initializing
    res = -1 
    
    # Verifying the column is not zeros
    test = 0
    for j in range(M.shape[0]):
        test += M[j,i]
        
    if (test > 0):
        
        for j in range(M.shape[0]):
            if (M[j,i] != 0):
                res = j # Lowest non-zero cell
                
    return res

In [5]:
def binomial(n,k): # Returns the binomial factor "k out of n"
    
    # Symmetry
    if ( k > (n-k) ):
        k = n-k
    
    # Initializing
    res = 1
    
    # Computing
    for i in range(1,k+1):
        res = res*(n-k+i)/i
        
    res = int(res)
    
    return res

In [6]:
def rank(M): # Returns the rank of the matrix supposedly triangular
    
    #Initializing
    res = 0
    
    # Going through the matrix
    for i in range(M.shape[1]):
        test = 0
        for j in range(M.shape[0]):
            test += M[j,i]
        if (test > 0):
            res += 1
            
    return res

In [40]:
def ones_possibilities(n,length,k): # Returns all possible fillings of a list
                             # of length n with k ones
    # Initializing
    L=[]

    for i in range(n):
        L.append([[0]*i + [1]*k + [0]*(length-k-i)])
        
    return L


In [8]:
def triangular(M): # Renders a matrix M a triangular one
    
    cols = M.shape[1]
    
    for i in range(1,cols):
        #lis = [low(M,j) for j in range(i)]
        j = 0
        while (j < i):
            if ((low(M,j) == low(M,i)) and (low(M,j) != -1)):
                M[:,i] = abs(M[:,i] - M[:,j])
                j = 0
            else:
                j+=1

In [31]:
def homologroups(d):
    
    n = d + 2 # Number of vertices of the simplicial complex enabling
              # the representation of S(d)
        
    res = []  # This list will conatain the dimensions of the homology
              # groups, in order of dimensionality
    
    
    rank_previous = 0 # Represents the rank of the map at the previous
                      # step
    
    card_previous = n # Cardinatlity of previous level: C(r-1)
    
    cols = n
    # Computing matrices of the maps, ranks and then dimension
    for i in range(1,n):
        
        # Computing the matrix' shape
        rows = cols
        cols = binomial(n,i+1)
        
        if (i < n-1):
            # Possibilities list
            L = ones_possibilities(rows, i+1)
        
            # Matrix
            M = np.transpose(np.array(L))
            print(M)
        
            # Rendering M triangular
            triangular(M)
            print(M)
            r = rank(M)
            print(r)
            answer = card_previous - r - rank_previous
            res.append(answer)
        
            # Updating the rank
            rank_previous = r
            card_previous = cols
        
        else:
            res.append(card_previous - rank_previous)
            
    print(res)
        

In [32]:
homologroups(1)
homologroups(2)

[[0 1 1]
 [1 0 1]
 [1 1 0]]
[[0 1 0]
 [1 1 0]
 [1 0 0]]
2
[1, 1]
[[0 0 0 1 1 1]
 [0 1 1 0 0 1]
 [1 0 1 0 1 0]
 [1 1 0 1 0 0]]
[[0 0 0 1 0 0]
 [0 1 0 1 0 0]
 [1 1 0 0 0 0]
 [1 0 0 0 0 0]]
3
[[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1]
 [0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 1]
 [1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 1 0]
 [1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 1 1 0 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
6
[1, -3, -2]


In [34]:
binomial(4,2)

6

In [41]:
ones_possibilities(4, 6, 3)

#len(ones_possibilities(6,2))

[[[1, 1, 1, 0, 0, 0]],
 [[0, 1, 1, 1, 0, 0]],
 [[0, 0, 1, 1, 1, 0]],
 [[0, 0, 0, 1, 1, 1]]]